/*
 * This file is generated by jOOQ.
 */
package com.manageway.jooq.pg_catalog.tables.records;


import com.manageway.jooq.pg_catalog.tables.Unnest;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UnnestRecord extends TableRecordImpl<UnnestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setUnnest(Object value) {
        set(0, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getUnnest() {
        return get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UnnestRecord
     */
    public UnnestRecord() {
        super(Unnest.UNNEST);
    }

    /**
     * Create a detached, initialised UnnestRecord
     */
    public UnnestRecord(Object unnest) {
        super(Unnest.UNNEST);

        setUnnest(unnest);
        resetChangedOnNotNull();
    }
}
