/*
 * This file is generated by jOOQ.
 */
package com.manageway.jooq.public_;


import com.manageway.jooq.public_.tables.Address;
import com.manageway.jooq.public_.tables.Customer;
import com.manageway.jooq.public_.tables.Employee;
import com.manageway.jooq.public_.tables.EmployeeCustomers;
import com.manageway.jooq.public_.tables.EmployeeProjects;
import com.manageway.jooq.public_.tables.Project;
import com.manageway.jooq.public_.tables.records.AddressRecord;
import com.manageway.jooq.public_.tables.records.CustomerRecord;
import com.manageway.jooq.public_.tables.records.EmployeeCustomersRecord;
import com.manageway.jooq.public_.tables.records.EmployeeProjectsRecord;
import com.manageway.jooq.public_.tables.records.EmployeeRecord;
import com.manageway.jooq.public_.tables.records.ProjectRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> ADDRESS_PKEY = Internal.createUniqueKey(Address.ADDRESS, DSL.name("address_pkey"), new TableField[] { Address.ADDRESS.ID }, true);
    public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_pkey"), new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final UniqueKey<CustomerRecord> UKR8WHBD0MF9ER6VWFR0SCLSXKD = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("ukr8whbd0mf9er6vwfr0sclsxkd"), new TableField[] { Customer.CUSTOMER.ADDRESS_ID }, true);
    public static final UniqueKey<EmployeeRecord> EMPLOYEE_PKEY = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("employee_pkey"), new TableField[] { Employee.EMPLOYEE.ID }, true);
    public static final UniqueKey<EmployeeRecord> UKQRBSK9LJMHFJE93ME0N7XWDXQ = Internal.createUniqueKey(Employee.EMPLOYEE, DSL.name("ukqrbsk9ljmhfje93me0n7xwdxq"), new TableField[] { Employee.EMPLOYEE.ADDRESS_ID }, true);
    public static final UniqueKey<ProjectRecord> PROJECT_PKEY = Internal.createUniqueKey(Project.PROJECT, DSL.name("project_pkey"), new TableField[] { Project.PROJECT.ID }, true);
    public static final UniqueKey<ProjectRecord> UKL035V0OX5H9CT820A40ELSJA = Internal.createUniqueKey(Project.PROJECT, DSL.name("ukl035v0ox5h9ct820a40elsja"), new TableField[] { Project.PROJECT.CUSTOMER_ID }, true);
    public static final UniqueKey<ProjectRecord> UKPO57PJX1GK21PJYVPE6WWOAC3 = Internal.createUniqueKey(Project.PROJECT, DSL.name("ukpo57pjx1gk21pjyvpe6wwoac3"), new TableField[] { Project.PROJECT.EMPLOYEE_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomerRecord, AddressRecord> CUSTOMER__FKGLKHKMH2VYN790IJS6HIQQPI = Internal.createForeignKey(Customer.CUSTOMER, DSL.name("fkglkhkmh2vyn790ijs6hiqqpi"), new TableField[] { Customer.CUSTOMER.ADDRESS_ID }, Keys.ADDRESS_PKEY, new TableField[] { Address.ADDRESS.ID }, true);
    public static final ForeignKey<EmployeeRecord, AddressRecord> EMPLOYEE__FKGA73HDTPB67TWLR9C1I337TYT = Internal.createForeignKey(Employee.EMPLOYEE, DSL.name("fkga73hdtpb67twlr9c1i337tyt"), new TableField[] { Employee.EMPLOYEE.ADDRESS_ID }, Keys.ADDRESS_PKEY, new TableField[] { Address.ADDRESS.ID }, true);
    public static final ForeignKey<EmployeeCustomersRecord, EmployeeRecord> EMPLOYEE_CUSTOMERS__FK39G7K2KR81EXXSJFMGHSNHW3Q = Internal.createForeignKey(EmployeeCustomers.EMPLOYEE_CUSTOMERS, DSL.name("fk39g7k2kr81exxsjfmghsnhw3q"), new TableField[] { EmployeeCustomers.EMPLOYEE_CUSTOMERS.EMPLOYEE_ID }, Keys.EMPLOYEE_PKEY, new TableField[] { Employee.EMPLOYEE.ID }, true);
    public static final ForeignKey<EmployeeCustomersRecord, CustomerRecord> EMPLOYEE_CUSTOMERS__FK63F2ACW1TLHYVCWPW2557699M = Internal.createForeignKey(EmployeeCustomers.EMPLOYEE_CUSTOMERS, DSL.name("fk63f2acw1tlhyvcwpw2557699m"), new TableField[] { EmployeeCustomers.EMPLOYEE_CUSTOMERS.CUSTOMER_ID }, Keys.CUSTOMER_PKEY, new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final ForeignKey<EmployeeProjectsRecord, EmployeeRecord> EMPLOYEE_PROJECTS__FK97JL81FSRBBLKQFOQWG2O7YPS = Internal.createForeignKey(EmployeeProjects.EMPLOYEE_PROJECTS, DSL.name("fk97jl81fsrbblkqfoqwg2o7yps"), new TableField[] { EmployeeProjects.EMPLOYEE_PROJECTS.EMPLOYEE_ID }, Keys.EMPLOYEE_PKEY, new TableField[] { Employee.EMPLOYEE.ID }, true);
    public static final ForeignKey<EmployeeProjectsRecord, ProjectRecord> EMPLOYEE_PROJECTS__FKIN7837PBK9GD6VAQYSD1SI8D4 = Internal.createForeignKey(EmployeeProjects.EMPLOYEE_PROJECTS, DSL.name("fkin7837pbk9gd6vaqysd1si8d4"), new TableField[] { EmployeeProjects.EMPLOYEE_PROJECTS.PROJECT_ID }, Keys.PROJECT_PKEY, new TableField[] { Project.PROJECT.ID }, true);
    public static final ForeignKey<ProjectRecord, CustomerRecord> PROJECT__FKJ948TRU2ILGQXFXSPPP9MOM5J = Internal.createForeignKey(Project.PROJECT, DSL.name("fkj948tru2ilgqxfxsppp9mom5j"), new TableField[] { Project.PROJECT.CUSTOMER_ID }, Keys.CUSTOMER_PKEY, new TableField[] { Customer.CUSTOMER.ID }, true);
    public static final ForeignKey<ProjectRecord, EmployeeRecord> PROJECT__FKOX7XSYL6K8FC7AQ1MPE8507HF = Internal.createForeignKey(Project.PROJECT, DSL.name("fkox7xsyl6k8fc7aq1mpe8507hf"), new TableField[] { Project.PROJECT.EMPLOYEE_ID }, Keys.EMPLOYEE_PKEY, new TableField[] { Employee.EMPLOYEE.ID }, true);
}
