/*
 * This file is generated by jOOQ.
 */
package com.manageway.jooq.pg_catalog.tables;


import com.manageway.jooq.pg_catalog.PgCatalog;
import com.manageway.jooq.pg_catalog.tables.records.PgTimezoneNamesRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.YearToSecond;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgTimezoneNames extends TableImpl<PgTimezoneNamesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pg_catalog.pg_timezone_names</code>
     */
    public static final PgTimezoneNames PG_TIMEZONE_NAMES = new PgTimezoneNames();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PgTimezoneNamesRecord> getRecordType() {
        return PgTimezoneNamesRecord.class;
    }

    /**
     * The column <code>pg_catalog.pg_timezone_names.name</code>.
     */
    public final TableField<PgTimezoneNamesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_timezone_names.abbrev</code>.
     */
    public final TableField<PgTimezoneNamesRecord, String> ABBREV = createField(DSL.name("abbrev"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.pg_timezone_names.utc_offset</code>.
     */
    public final TableField<PgTimezoneNamesRecord, YearToSecond> UTC_OFFSET = createField(DSL.name("utc_offset"), SQLDataType.INTERVAL, this, "");

    /**
     * The column <code>pg_catalog.pg_timezone_names.is_dst</code>.
     */
    public final TableField<PgTimezoneNamesRecord, Boolean> IS_DST = createField(DSL.name("is_dst"), SQLDataType.BOOLEAN, this, "");

    private PgTimezoneNames(Name alias, Table<PgTimezoneNamesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PgTimezoneNames(Name alias, Table<PgTimezoneNamesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "pg_timezone_names" as  SELECT name,
         abbrev,
         utc_offset,
         is_dst
        FROM pg_timezone_names() pg_timezone_names(name, abbrev, utc_offset, is_dst);
        """), where);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_timezone_names</code> table
     * reference
     */
    public PgTimezoneNames(String alias) {
        this(DSL.name(alias), PG_TIMEZONE_NAMES);
    }

    /**
     * Create an aliased <code>pg_catalog.pg_timezone_names</code> table
     * reference
     */
    public PgTimezoneNames(Name alias) {
        this(alias, PG_TIMEZONE_NAMES);
    }

    /**
     * Create a <code>pg_catalog.pg_timezone_names</code> table reference
     */
    public PgTimezoneNames() {
        this(DSL.name("pg_timezone_names"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PgCatalog.PG_CATALOG;
    }

    @Override
    public PgTimezoneNames as(String alias) {
        return new PgTimezoneNames(DSL.name(alias), this);
    }

    @Override
    public PgTimezoneNames as(Name alias) {
        return new PgTimezoneNames(alias, this);
    }

    @Override
    public PgTimezoneNames as(Table<?> alias) {
        return new PgTimezoneNames(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PgTimezoneNames rename(String name) {
        return new PgTimezoneNames(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgTimezoneNames rename(Name name) {
        return new PgTimezoneNames(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PgTimezoneNames rename(Table<?> name) {
        return new PgTimezoneNames(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgTimezoneNames where(Condition condition) {
        return new PgTimezoneNames(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgTimezoneNames where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgTimezoneNames where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgTimezoneNames where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgTimezoneNames where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgTimezoneNames where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgTimezoneNames where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PgTimezoneNames where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgTimezoneNames whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PgTimezoneNames whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
