/*
 * This file is generated by jOOQ.
 */
package com.manageway.jooq.public_.tables;


import com.manageway.jooq.public_.Keys;
import com.manageway.jooq.public_.Public;
import com.manageway.jooq.public_.tables.Customer.CustomerPath;
import com.manageway.jooq.public_.tables.Employee.EmployeePath;
import com.manageway.jooq.public_.tables.records.EmployeeCustomersRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeeCustomers extends TableImpl<EmployeeCustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.employee_customers</code>
     */
    public static final EmployeeCustomers EMPLOYEE_CUSTOMERS = new EmployeeCustomers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EmployeeCustomersRecord> getRecordType() {
        return EmployeeCustomersRecord.class;
    }

    /**
     * The column <code>public.employee_customers.employee_id</code>.
     */
    public final TableField<EmployeeCustomersRecord, UUID> EMPLOYEE_ID = createField(DSL.name("employee_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.employee_customers.id</code>.
     */
    public final TableField<EmployeeCustomersRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.employee_customers.created_at</code>.
     */
    public final TableField<EmployeeCustomersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.employee_customers.tenant_id</code>.
     */
    public final TableField<EmployeeCustomersRecord, UUID> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.employee_customers.updated_at</code>.
     */
    public final TableField<EmployeeCustomersRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.employee_customers.customer_id</code>.
     */
    public final TableField<EmployeeCustomersRecord, UUID> CUSTOMER_ID = createField(DSL.name("customer_id"), SQLDataType.UUID, this, "");

    private EmployeeCustomers(Name alias, Table<EmployeeCustomersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EmployeeCustomers(Name alias, Table<EmployeeCustomersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.employee_customers</code> table reference
     */
    public EmployeeCustomers(String alias) {
        this(DSL.name(alias), EMPLOYEE_CUSTOMERS);
    }

    /**
     * Create an aliased <code>public.employee_customers</code> table reference
     */
    public EmployeeCustomers(Name alias) {
        this(alias, EMPLOYEE_CUSTOMERS);
    }

    /**
     * Create a <code>public.employee_customers</code> table reference
     */
    public EmployeeCustomers() {
        this(DSL.name("employee_customers"), null);
    }

    public <O extends Record> EmployeeCustomers(Table<O> path, ForeignKey<O, EmployeeCustomersRecord> childPath, InverseForeignKey<O, EmployeeCustomersRecord> parentPath) {
        super(path, childPath, parentPath, EMPLOYEE_CUSTOMERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EmployeeCustomersPath extends EmployeeCustomers implements Path<EmployeeCustomersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EmployeeCustomersPath(Table<O> path, ForeignKey<O, EmployeeCustomersRecord> childPath, InverseForeignKey<O, EmployeeCustomersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EmployeeCustomersPath(Name alias, Table<EmployeeCustomersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EmployeeCustomersPath as(String alias) {
            return new EmployeeCustomersPath(DSL.name(alias), this);
        }

        @Override
        public EmployeeCustomersPath as(Name alias) {
            return new EmployeeCustomersPath(alias, this);
        }

        @Override
        public EmployeeCustomersPath as(Table<?> alias) {
            return new EmployeeCustomersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<EmployeeCustomersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.EMPLOYEE_CUSTOMERS__FK39G7K2KR81EXXSJFMGHSNHW3Q, Keys.EMPLOYEE_CUSTOMERS__FK63F2ACW1TLHYVCWPW2557699M);
    }

    private transient EmployeePath _employee;

    /**
     * Get the implicit join path to the <code>public.employee</code> table.
     */
    public EmployeePath employee() {
        if (_employee == null)
            _employee = new EmployeePath(this, Keys.EMPLOYEE_CUSTOMERS__FK39G7K2KR81EXXSJFMGHSNHW3Q, null);

        return _employee;
    }

    private transient CustomerPath _customer;

    /**
     * Get the implicit join path to the <code>public.customer</code> table.
     */
    public CustomerPath customer() {
        if (_customer == null)
            _customer = new CustomerPath(this, Keys.EMPLOYEE_CUSTOMERS__FK63F2ACW1TLHYVCWPW2557699M, null);

        return _customer;
    }

    @Override
    public EmployeeCustomers as(String alias) {
        return new EmployeeCustomers(DSL.name(alias), this);
    }

    @Override
    public EmployeeCustomers as(Name alias) {
        return new EmployeeCustomers(alias, this);
    }

    @Override
    public EmployeeCustomers as(Table<?> alias) {
        return new EmployeeCustomers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeeCustomers rename(String name) {
        return new EmployeeCustomers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeeCustomers rename(Name name) {
        return new EmployeeCustomers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EmployeeCustomers rename(Table<?> name) {
        return new EmployeeCustomers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeCustomers where(Condition condition) {
        return new EmployeeCustomers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeCustomers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeCustomers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeCustomers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeCustomers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeCustomers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeCustomers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EmployeeCustomers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeCustomers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EmployeeCustomers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
