/*
 * This file is generated by jOOQ.
 */
package com.manageway.jooq.public_.tables.records;


import com.manageway.jooq.public_.tables.EmployeeCustomers;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EmployeeCustomersRecord extends TableRecordImpl<EmployeeCustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.employee_customers.employee_id</code>.
     */
    public void setEmployeeId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.employee_customers.employee_id</code>.
     */
    public UUID getEmployeeId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.employee_customers.id</code>.
     */
    public void setId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.employee_customers.id</code>.
     */
    public UUID getId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.employee_customers.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.employee_customers.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.employee_customers.tenant_id</code>.
     */
    public void setTenantId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.employee_customers.tenant_id</code>.
     */
    public UUID getTenantId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.employee_customers.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.employee_customers.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.employee_customers.customer_id</code>.
     */
    public void setCustomerId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.employee_customers.customer_id</code>.
     */
    public UUID getCustomerId() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeCustomersRecord
     */
    public EmployeeCustomersRecord() {
        super(EmployeeCustomers.EMPLOYEE_CUSTOMERS);
    }

    /**
     * Create a detached, initialised EmployeeCustomersRecord
     */
    public EmployeeCustomersRecord(UUID employeeId, UUID id, LocalDateTime createdAt, UUID tenantId, LocalDateTime updatedAt, UUID customerId) {
        super(EmployeeCustomers.EMPLOYEE_CUSTOMERS);

        setEmployeeId(employeeId);
        setId(id);
        setCreatedAt(createdAt);
        setTenantId(tenantId);
        setUpdatedAt(updatedAt);
        setCustomerId(customerId);
        resetChangedOnNotNull();
    }
}
