/*
 * This file is generated by jOOQ.
 */
package com.manageway.jooq.public_.tables.records;


import com.manageway.jooq.public_.tables.Project;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.project.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.project.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.project.tenant_id</code>.
     */
    public void setTenantId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.project.tenant_id</code>.
     */
    public UUID getTenantId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.project.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.project.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.project.end_date</code>.
     */
    public void setEndDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.project.end_date</code>.
     */
    public LocalDateTime getEndDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.project.start_date</code>.
     */
    public void setStartDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.project.start_date</code>.
     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.project.title</code>.
     */
    public void setTitle(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.project.title</code>.
     */
    public String getTitle() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.project.total_price</code>.
     */
    public void setTotalPrice(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.project.total_price</code>.
     */
    public Double getTotalPrice() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.project.customer_id</code>.
     */
    public void setCustomerId(UUID value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.project.customer_id</code>.
     */
    public UUID getCustomerId() {
        return (UUID) get(8);
    }

    /**
     * Setter for <code>public.project.employee_id</code>.
     */
    public void setEmployeeId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.project.employee_id</code>.
     */
    public UUID getEmployeeId() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(UUID id, LocalDateTime createdAt, UUID tenantId, LocalDateTime updatedAt, LocalDateTime endDate, LocalDateTime startDate, String title, Double totalPrice, UUID customerId, UUID employeeId) {
        super(Project.PROJECT);

        setId(id);
        setCreatedAt(createdAt);
        setTenantId(tenantId);
        setUpdatedAt(updatedAt);
        setEndDate(endDate);
        setStartDate(startDate);
        setTitle(title);
        setTotalPrice(totalPrice);
        setCustomerId(customerId);
        setEmployeeId(employeeId);
        resetChangedOnNotNull();
    }
}
